apps/auctions/urls.py
from django.urls import path

from .views import AuctionCreateView, AuctionDetailView, AuctionListView, AuctionUpdateView, delete_auction


app_name = 'auctions'

urlpatterns = [
    path('list', AuctionListView.as_view(), name='auction_list'),
    path('create', AuctionCreateView.as_view(), name='auction_create'),
    path('<int:pk>', AuctionDetailView.as_view(), name='auction_detail'),
    path('<int:pk>/update', AuctionUpdateView.as_view(), name='auction_update'),
    path('<int:pk>/delete/<int:from_detail>', delete_auction, name='auction_delete'),
]

apps/dashboard/urls.py
from django.urls import path

from .views import MainView


app_name = 'dashboard'

urlpatterns = [
    path('', MainView.as_view(), name='main'),
]

apps/offers/urls.py
from django.urls import path

from .views import OfferCreateView, OfferListView


app_name = 'offers'

urlpatterns = [
    path('list', OfferListView.as_view(), name='offer_list'),
    path('create/for-auction=<int:auction_pk>', OfferCreateView.as_view(), name='offer_create'),
]

project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('apps.dashboard.urls', namespace='dashboard')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('auctions/', include('apps.auctions.urls', namespace='auctions')),
    path('offers/', include('apps.offers.urls', namespace='offers')),
]

if settings.DEBUG:
    urlpatterns += [
        path('admin/', admin.site.urls),
        path('__debug__/', include('debug_toolbar.urls')),
    ]

apps/auctions/models.py
from datetime import timedelta

from django.db import models
from django.urls import reverse
from django_q.models import Schedule


class Service(models.Model):
    CATEGORY_CHOICES = (
        (1, "Repair"),
        (2, "Maintenance"),
    )

    name = models.CharField(max_length=128)
    category = models.PositiveSmallIntegerField(choices=CATEGORY_CHOICES)

    def __str__(self):
        return f'{str(self.get_category_display())}. {self.name}'


class Auction(models.Model):
    FAST = 10
    NORMAL = 60
    SLOW = 1440

    DURATION_CHOICES = (
        (FAST, '10 minutes'),
        (NORMAL, '1 hour'),
        (SLOW, '1 day'),
    )

    car = models.ForeignKey('accounts.Car', on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    start_cost = models.PositiveSmallIntegerField()

    datetime_start = models.DateTimeField(auto_now_add=True)
    duration_choice = models.PositiveSmallIntegerField(choices=DURATION_CHOICES, default=FAST)
    datetime_end = models.DateTimeField(blank=True, null=True)

    is_ended = models.BooleanField(default=False)

    def __str__(self):
        return f'Auction on {self.service} for {self.car.client.user.email}'

    def get_absolute_url(self):
        return reverse('auctions:auction_detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        if not self.pk:
            super(Auction, self).save(*args, **kwargs)

        if not self.datetime_end:
            datetime_end = self.datetime_start + timedelta(minutes=self.duration_choice)
            self.datetime_end = datetime_end

        super(Auction, self).save(*args, **kwargs)


class Order(models.Model):
    offer = models.OneToOneField('offers.Offer', on_delete=models.CASCADE)
    datetime_start = models.DateTimeField(auto_now_add=True)
    is_completed = models.BooleanField(default=False)

    def __str__(self):
        return f'Order №{self.pk}'

apps/auctions/forms.py
from django import forms

from apps.accounts.models import Car

from .models import Auction, Service


class AuctionCreationForm(forms.ModelForm):
    service = forms.ModelChoiceField(queryset=Service.objects.all())
    duration_choice = forms.ChoiceField(choices=Auction.DURATION_CHOICES)

    class Meta:
        model = Auction
        fields = ['car', 'service', 'start_cost', 'duration_choice']

    def __init__(self, user, *args, **kwargs):
        super(AuctionCreationForm, self).__init__(*args, **kwargs)
        self.fields['car'] = forms.ModelChoiceField(queryset=Car.objects.filter(client__user=user))

auctions/forms.py
from django import forms

from accounts.models import Car

from .models import Auction, Service


class AuctionCreationForm(forms.ModelForm):
    service = forms.ModelChoiceField(queryset=Service.objects.all())
    duration_choice = forms.ChoiceField(choices=Auction.DURATION_CHOICES)

    class Meta:
        model = Auction
        fields = ['car', 'service', 'start_cost', 'duration_choice']

    def __init__(self, user, *args, **kwargs):
        super(AuctionCreationForm, self).__init__(*args, **kwargs)
        self.fields['car'] = forms.ModelChoiceField(queryset=Car.objects.filter(client__user=user))

apps/auctions/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_http_methods
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django.urls import reverse

from .forms import AuctionCreationForm
from .models import Auction


class AuctionListView(ListView):
    model = Auction
    context_object_name = 'auctions'
    template_name = 'auctions/auction_list.html'

    def get_queryset(self):
        user = self.request.user

        if user.is_client:
            queryset = Auction.objects.filter(car__client__user=user).select_related('service')
        elif user.is_representative:
            queryset = Auction.objects.filter(
                is_ended=False, service__in=user.representative.company.services.all()).select_related('service')
        else:
            queryset = Auction.objects.all()

        return queryset


class AuctionCreateView(CreateView):
    model = Auction
    form_class = AuctionCreationForm
    template_name = 'auctions/auction_create.html'

    def get_form_kwargs(self):
        kwargs = super(AuctionCreateView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs


class AuctionDetailView(DetailView):
    model = Auction
    queryset = Auction.objects.select_related('car', 'car__client__user', 'service')
    template_name = 'auctions/auction_detail.html'


class AuctionUpdateView(UpdateView):
    model = Auction
    form_class = AuctionCreationForm
    template_name = 'auctions/auction_update.html'

    def get_form_kwargs(self):
        kwargs = super(AuctionUpdateView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs


@require_http_methods(['DELETE'])
def delete_auction(request, pk: int, from_detail: int):
    auction = get_object_or_404(Auction, pk=pk)
    auction.delete()

    if from_detail:
        response = HttpResponse()
        response["HX-Redirect"] = reverse('auctions:auction_list')
        return response

    return render(request, 'auctions/auctions_items.html', {
        'auctions': Auction.objects.select_related('car', 'car__client__user', 'service')})

templates/auctions/auction_create.html
<form method="post" hx-post="{% url 'auctions:auction_create' %}" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}' hx-target="#auction-list">
  <div class="row g-3">
    <div class="col-3">
      <select class="form-select" id="id_car" name="car">
        <option selected>Choose a car</option>
        {% for car in form.car.field.queryset %}
          <option value="{{ car.id }}">{{ car }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="col-3">
      {% regroup form.service.field.queryset by get_category_display as categories %}
      <select class="form-select" id="id_service" name="service">
        <option selected>Choose a service</option>
        {% for category in categories %}
          <optgroup label="{{ category.grouper }}">
            {% for service in category.list %}
              <option value="{{ service.id }}">{{ service.name }}</option>
            {% endfor %}
          </optgroup>
        {% endfor %}
      </select>
    </div>
    <div class="col-3">
      <select class="form-select" id="id_duration_choice" name="duration_choice">
        <option selected>Choose a duration</option>
        {% for duration in form.fields.duration_choice.choices %}
          <option value="{{ duration.0 }}">{{ duration.1 }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="col-3">
      <div class="input-group">
        <span class="input-group-text">$</span>
        <input class="form-control" type="number" name="start_cost" placeholder="Enter starting price" required id="id_start_cost">
      </div>
    </div>
    <div class="col-12">
      <button id="auction_create" class="btn btn-primary btn" type="submit">Start auction</button>
    </div>
  </div>
</form>

templates/auctions/auction_detail.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
  <script src="{% static 'js/htmx.min.js' %}"></script>
{% endblock %}

{% block content %}
  <div class="row g-3 mt-3">
      <div class="col-12">
        <div class="card bg-dark">
          <h5 class="card-header">
            <nav class="pt-2 ps-2">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'dashboard:main' %}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{% url 'auctions:auction_list' %}">Auctions</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ auction }}</li>
              </ol>
            </nav>
          </h5>
          <div class="card-body">
            <h1 class="display-1">
              <strong>Service:</strong> {{ auction.service.name }}
            </h1>
            <h1 class="display-6 text-muted"><strong>Category:</strong> {{ auction.service.get_category_display }}</h1>
            <dl class="row mt-5">
              <dt class="col-lg-1">Client</dt>
              <dd class="col-lg-11">
                <p>{{ auction.car.client.user.full_name }}</p>
                <p>{{ auction.car.client.user.email }}</p>
              </dd>
              <dt class="col-lg-1">Car</dt>
              <dd class="col-lg-11">{{ auction.car.release_year }} {{ auction.car.brand }} {{ auction.car.model }} {{ auction.car.color }}</dd>
              <dt class="col-lg-1">Time</dt>
              <dd class="col-lg-11">{{ auction.duration_choice }}</dd>
            </dl>
            <div class="row mt-5">
              <div class="col">
                {% if request.user.is_client %}
                  <a href="{% url 'auctions:auction_update' auction.pk %}" class="btn btn-primary">Edit</a>
                <a hx-delete="{% url 'auctions:auction_delete' auction.pk 1 %}" hx-confirm="Are you sure you want to delete this auction?" class="btn btn-danger">Delete</a>
                {% elif request.user.is_representative %}
                  <a href="{% url 'offers:offer_create' auction.pk %}" class="btn btn-primary me-2">Make an offer</a>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
{% endblock %}

templates/auctions/auction_list.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
  <script src="{% static 'js/htmx.min.js' %}"></script>
{% endblock %}

{% block content %}
  <h1 class="display-1">Auctions</h1>
  {% include 'auctions/auctions_items.html' %}
{% endblock %}

templates/auctions/auction_update.html
{% extends 'base.html' %}

{% block content %}
  <div class="mx-auto col-lg-8 card bg-dark">
    <div class="row">
      <div class="col-lg-6 col-md-5 col-sm-12">
        <div class="card-body">
          <h1>Edit auction</h1>
          <h3>{{ auction }}</h3>
          <dl class="row mt-3">
            <dt class="col-3 col-md-2 col-lg-2">Car</dt>
            <dd class="col-9 col-md-10 col-lg-10">{{ auction.car }}</dd>
          </dl>
        </div>
      </div>
      <div class="col-lg-6 col-md-7 col-sm-12">
        <div class="card-body">
          <form class="row g-3" action="{% url 'auctions:auction_update' auction.pk %}" method="post">
            {% csrf_token %}
            {{ form.errors }}
            <input type="hidden" id="id_car" name="car" value="{{ auction.car.id }}">
            <div class="col-12">
              {% regroup form.service.field.queryset by get_category_display as categories %}
              <select class="form-select" id="id_service" name="service">
                <option>Choose a service</option>
                {% for category in categories %}
                  <optgroup label="{{ category.grouper }}">
                    {% for service in category.list %}
                      <option {% if form.initial.service == service.id %}selected{% endif %} value="{{ service.id }}">{{ service.name }}</option>
                    {% endfor %}
                  </optgroup>
                {% endfor %}
              </select>
            </div>
            <div class="col-12">
            {{ form.duration.value }}
              <select class="form-select" id="id_duration_choice" name="duration_choice">
                <option>Choose a duration</option>
                {% for duration in form.fields.duration_choice.choices %}
                  <option {% if form.initial.duration_choice == duration.0 %}selected{% endif %} value="{{ duration.0 }}">{{ duration.1 }}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-12">
              <div class="input-group">
                <span class="input-group-text">$</span>
                <input class="form-control" type="number" name="start_cost" placeholder="Enter starting price" value="{{ form.start_cost.value }}" readonly id="id_start_cost">
              </div>
            </div>
            <div class="d-flex justify-content-center">
              <button class="btn btn-primary" type="submit">Save</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/auctions/auctions_items.html
<div class="row g-3 mt-3" id="auctions" hx-confirm="Are you sure you want to delete this auction?" hx-target="#auctions" hx-swap="outerHTML">
  {% if request.user.is_client %}
    <div class="col-12 col-lg-4 col-md-6">
      <div class="card bg-dark">
        <div class="card-body">
          <h4 class="card-title">Create new auction</h4>
          <p class="card-text">Lorem ipsum dolor amet</p>
          <a href="{% url 'auctions:auction_create' %}" class="btn btn-primary">Create</a>
        </div>
      </div>
    </div>
  {% endif %}
  {% for auction in auctions %}
    <div class="col-12 col-lg-4 col-md-6">
      <div class="card bg-dark">
        <div class="card-body">
          <h4 class="card-title"><a href="{{ auction.get_absolute_url }}">{{ auction.service }}</a></h4>
          <p class="card-text">
            <small>{{ auction.datetime_end|date:'Y-m-d H:i:s' }}</small>
          </p>
          <div class="btn-toolbar" role="toolbar">
            {% if request.user.is_client %}
              <a href="{% url 'auctions:auction_update' auction.pk %}" class="btn btn-primary me-2">Edit</a>
              <a class="btn btn-danger" hx-delete="{% url 'auctions:auction_delete' auction.pk 0 %}">Delete</a>
            {% elif request.user.is_representative %}
              <a href="{% url 'offers:offer_create' auction.pk %}" class="btn btn-primary me-2">Make an offer</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
</div>