accounts/urls.py
from django.contrib.auth.views import TemplateView, PasswordChangeView, LogoutView
from django.urls import path, reverse_lazy

from .views import (
    SignInView, SignUpView,
    CarListView, CarDetailView, CarCreateView, CarUpdateView, CarDeleteView,
    CompanyListView, CompanyDetailView, CompanyCreateView, CompanyUpdateView, CompanyDeleteView
)


app_name = 'accounts'

urlpatterns = [
    path('sign-up', SignUpView.as_view(), name='sign_up'),
    path('sign-in', SignInView.as_view(), name='sign_in'),
    path('choose-account', TemplateView.as_view(
        template_name='accounts/choose_account.html'),
        name='choose_account'
    ),
    path('change-password', PasswordChangeView.as_view(
        template_name='accounts/password_change.html',
        success_url=reverse_lazy('dashboard:main'),
        extra_context={'password_change': True}
    ), name='password_change'),
    path('logout', LogoutView.as_view(
        next_page='/'
    ), name='logout'),

    path('cars', CarListView.as_view(), name='car_list'),
    path('cars/<int:pk>', CarDetailView.as_view(), name='car_detail'),
    path('cars/create', CarCreateView.as_view(), name='car_create'),
    path('cars/<int:pk>/edit', CarUpdateView.as_view(), name='car_edit'),
    path('cars/<int:pk>/delete', CarDeleteView.as_view(), name='car_delete'),

    path('companies', CompanyListView.as_view(), name='company_list'),
    path('companies/<int:pk>', CompanyDetailView.as_view(), name='company_detail'),
    path('companies/create', CompanyCreateView.as_view(), name='company_create'),
    path('companies/<int:pk>/edit', CompanyUpdateView.as_view(), name='company_edit'),
    path('companies/<int:pk>/delete', CompanyDeleteView.as_view(), name='company_delete'),
]

apps/accounts/urls.py
from django.contrib.auth.views import TemplateView, PasswordChangeView, LogoutView
from django.urls import path, reverse_lazy

from .views import (
    SignInView, SignUpView,
    CarListView, CarDetailView, CarCreateView, CarUpdateView, CarDeleteView,
    CompanyListView, CompanyDetailView, CompanyCreateView, CompanyUpdateView, CompanyDeleteView
)


app_name = 'accounts'

urlpatterns = [
    path('sign-up', SignUpView.as_view(), name='sign_up'),
    path('sign-in', SignInView.as_view(), name='sign_in'),
    path('choose-account', TemplateView.as_view(
        template_name='accounts/choose_account.html'),
         name='choose_account'
         ),
    path('change-password', PasswordChangeView.as_view(
        template_name='accounts/password_change.html',
        success_url=reverse_lazy('dashboard:main'),
        extra_context={'password_change': True}
    ), name='password_change'),
    path('logout', LogoutView.as_view(
        next_page='/'
    ), name='logout'),

    path('cars', CarListView.as_view(), name='car_list'),
    path('cars/<int:pk>', CarDetailView.as_view(), name='car_detail'),
    path('cars/create', CarCreateView.as_view(), name='car_create'),
    path('cars/<int:pk>/update', CarUpdateView.as_view(), name='car_update'),
    path('cars/<int:pk>/delete', CarDeleteView.as_view(), name='car_delete'),

    path('companies', CompanyListView.as_view(), name='company_list'),
    path('companies/<int:pk>', CompanyDetailView.as_view(), name='company_detail'),
    path('companies/create', CompanyCreateView.as_view(), name='company_create'),
    path('companies/<int:pk>/update', CompanyUpdateView.as_view(), name='company_update'),
    path('companies/<int:pk>/delete', CompanyDeleteView.as_view(), name='company_delete'),
]

project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('apps.dashboard.urls', namespace='dashboard')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('auctions/', include('apps.auctions.urls', namespace='auctions')),
    path('offers/', include('apps.offers.urls', namespace='offers')),
]

if settings.DEBUG:
    urlpatterns += [
        path('admin/', admin.site.urls),
        path('__debug__/', include('debug_toolbar.urls')),
    ]

apps/accounts/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models

from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name}'.strip()

    @property
    def is_client(self):
        return hasattr(self, 'client')

    @property
    def is_representative(self):
        return hasattr(self, 'representative')


class Company(models.Model):
    name = models.CharField(max_length=128)
    services = models.ManyToManyField('auctions.Service', blank=True)
    email = models.EmailField(unique=True)

    class Meta:
        verbose_name_plural = 'companies'


class Representative(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['user', 'company']


class Client(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f'Client №{self.pk}'


class Car(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    brand = models.CharField(max_length=128)
    model = models.CharField(max_length=128)
    color = models.CharField(max_length=128)
    release_year = models.CharField(max_length=4)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from auctions.models import Service
from .models import User, Car, Company


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'password1', 'password2']

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class CarCreationForm(forms.ModelForm):
    brand = forms.CharField(max_length=128)
    color = forms.CharField(max_length=128)
    release_year = forms.CharField(max_length=4)
    model = forms.CharField(max_length=128)

    class Meta:
        model = Car
        fields = ['brand', 'color', 'release_year', 'model']


class CompanyCreationForm(forms.ModelForm):
    name = forms.CharField(max_length=128)
    services = forms.ModelMultipleChoiceField(
        queryset=Service.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )
    email = forms.EmailField(required=True)

    class Meta:
        model = Company
        fields = ['name', 'services', 'email']

apps/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from apps.auctions.models import Service
from .models import User, Car, Company


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'password1', 'password2']

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class CarCreationForm(forms.ModelForm):
    brand = forms.CharField(max_length=128, required=True)
    model = forms.CharField(max_length=128, required=True)
    color = forms.CharField(max_length=128, required=True)
    release_year = forms.CharField(max_length=4, required=True)

    class Meta:
        model = Car
        fields = ['brand', 'model', 'color', 'release_year']


class CompanyCreationForm(forms.ModelForm):
    name = forms.CharField(max_length=128, required=True)
    services = forms.ModelMultipleChoiceField(
        queryset=Service.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    email = forms.EmailField(required=True)

    class Meta:
        model = Company
        fields = ['name', 'services', 'email']

apps/accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
from django.urls import reverse_lazy
from django.shortcuts import redirect

from .forms import SignUpForm, CarCreationForm, CompanyCreationForm
from .models import Client, Car, Company, Representative


class SignUpView(CreateView):
    template_name = 'accounts/sign_up.html'
    form_class = SignUpForm
    success_url = reverse_lazy('accounts:choose_account')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user, backend='django.contrib.auth.backends.ModelBackend')

        return redirect(self.success_url)


class SignInView(LoginView):
    template_name = 'accounts/sign_in.html'
    next_page = '/'

    def form_valid(self, form):
        remember_me = form.cleaned_data.get('remember_me')

        if not remember_me:
            self.request.session.set_expiry(0)
            self.request.session.modified = True

        return super(SignInView, self).form_valid(form)


class CarListView(ListView):
    model = Car
    template_name = 'accounts/car_list.html'


class CarDetailView(DetailView):
    model = Car
    template_name = 'accounts/car_detail.html'


class CarCreateView(CreateView):
    model = Car
    form_class = CarCreationForm
    template_name = 'accounts/car_create.html'
    success_url = '/'

    def form_valid(self, form):
        client = Client.objects.create(user=self.request.user)
        form.instance.client = client
        return super(CarCreateView, self).form_valid(form)


class CarUpdateView(UpdateView):
    model = Car
    form_class = CarCreationForm
    template_name = 'accounts/car_update.html'
    success_url = '/'


class CarDeleteView(DeleteView):
    model = Car
    success_url = reverse_lazy('dashboard:main')


class CompanyListView(ListView):
    model = Company
    template_name = 'accounts/company_list.html'


class CompanyDetailView(DetailView):
    model = Company
    template_name = 'accounts/company_detail.html'


class CompanyCreateView(CreateView):
    model = Company
    form_class = CompanyCreationForm
    template_name = 'accounts/company_create.html'

    def get_success_url(self):
        Representative.objects.create(
            user=self.request.user,
            company=self.object
        )
        return reverse_lazy('dashboard:main')


class CompanyUpdateView(UpdateView):
    model = Company
    form_class = CompanyCreationForm
    template_name = 'accounts/company_update.html'
    success_url = '/'


class CompanyDeleteView(DeleteView):
    model = Company
    success_url = reverse_lazy('dashboard:main')

templates/accounts/car_create.html
{% extends 'base.html' %}

{% block content %}
  <div class="row g-3 mb-5">
    <h1 class="display-1">Add Your Car</h1>
    <form class="row g-3" action="{% url 'accounts:car_create' %}" method="post">
      {% csrf_token %}
      {{ form.errors }}
      <div class="col-12 col-lg-6">
        <label class="form-label" for="id_brand">Brand</label>
        <input type="text" class="form-control" name="brand" id="id_brand" maxlength="128" required placeholder="Enter automobile brand name of your car">
      </div>
      <div class="col-12 col-lg-6">
        <label class="form-label" for="id_model">Model</label>
        <input type="text" class="form-control" name="model" id="id_model" maxlength="128" required placeholder="Enter model name of your car">
      </div>
      <div class="col-12 col-lg-6">
        <label class="form-label" for="id_color">Color</label>
        <input type="text" class="form-control" name="color" id="id_color" maxlength="128" required placeholder="Enter color of your car">
      </div>
      <div class="col-12 col-lg-6">
        <label class="form-label" for="id_release_year">Release Year</label>
        <input type="text" class="form-control" name="release_year" id="id_release_year" maxlength="4" required placeholder="Enter release year of your car">
      </div>
      <div class="d-flex justify-content-center mt-5">
        <button class="btn btn-lg btn-outline-light" type="submit">Add</button>
      </div>
    </form>
  </div>
{% endblock %}

templates/accounts/car_update.html
{% extends 'base.html' %}

{% block content %}
  <div class="row g-3 mb-5">
    <h1 class="display-1">Change Your Car</h1>
    <form class="row g-3" action="{% url 'accounts:car_edit' car.pk %}" method="post">
      {% csrf_token %}
      {{ form.errors }}
      <div class="col-12 col-lg-6">
        <label class="form-label" for="id_brand">Brand</label>
        <input type="text" class="form-control" name="brand" id="id_brand" maxlength="128" required value="{{ car.brand }}" placeholder="Enter automobile brand name of your car">
      </div>
      <div class="col-12 col-lg-6">
        <label class="form-label" for="id_model">Model</label>
        <input type="text" class="form-control" name="model" id="id_model" maxlength="128" required value="{{ car.model }}" placeholder="Enter model name of your car">
      </div>
      <div class="col-12 col-lg-6">
        <label class="form-label" for="id_color">Color</label>
        <input type="text" class="form-control" name="color" id="id_color" maxlength="128" required value="{{ car.color }}" placeholder="Enter color of your car">
      </div>
      <div class="col-12 col-lg-6">
        <label class="form-label" for="id_release_year">Release Year</label>
        <input type="text" class="form-control" name="release_year" id="id_release_year" maxlength="4" required value="{{ car.release_year }}" placeholder="Enter release year of your car">
      </div>
      <div class="d-flex justify-content-center mt-5">
        <button class="btn btn-lg btn-outline-light" type="submit">Save</button>
      </div>
    </form>
  </div>
{% endblock %}

templates/accounts/choose_account.html
{% extends 'base.html' %}

{% block content %}
  <div class="row g-3 mb-5">
    <h1 class="display-1">Choose the type of your account</h1>
    <div class="col-12 col-lg-6">
      <a href="{% url 'accounts:car_create' %}" class="card bg-dark" style="height: 274px; text-decoration: none;">
        <div class="card-body d-flex align-items-center justify-content-center">
          <h3 class="display-3 text-center">I am a client</h3>
        </div>
      </a>
    </div>
    <div class="col-12 col-lg-6">
      <a href="{% url 'accounts:company_create' %}" class="card bg-dark" style="height: 274px; text-decoration: none;">
        <div class="card-body d-flex align-items-center justify-content-center">
          <h3 class="display-3 text-center">I am a representative</h3>
        </div>
      </a>
    </div>
  </div>
{% endblock %}

templates/accounts/company_create.html
{% extends 'base.html' %}

{% block content %}
  <div class="row g-3 mb-5">
    <h1 class="display-1">Add Your Company</h1>
    <form class="row g-3" action="{% url 'accounts:company_create' %}" method="post">
      {% csrf_token %}
      {{ form.errors }}
      <div class="col-12 col-lg-6">
        <label class="form-label" for="id_name">Name of Company</label>
        <input type="text" class="form-control" name="name" id="id_name" maxlength="128" required placeholder="Enter your company name">
      </div>
      <div class="col-12 col-lg-6">
        <label class="form-label" for="id_email">Company Email</label>
        <input type="text" class="form-control" name="email" id="id_email" maxlength="128" required placeholder="Enter your company email">
      </div>
      <div class="col-12 col-lg-6">
        <label class="form-label" for="id_color">Choose Provided Services</label>
        {% regroup form.services.field.queryset by get_category_display as categories %}
        {% for category in categories %}
          <h6 class="mt-2">{{ category.grouper }}</h6>
          {% for service in category.list %}
            <div class="form-check">
              <input class="form-check-input" type="checkbox" name="services" value="{{ service.id }}" id="id_services_{{ service.id|add:-1 }}">
              <label class="form-check-label text-white" for="id_services_{{ service.id|add:-1 }}">{{ service.name }}</label>
            </div>
          {% endfor %}
        {% endfor %}
      </div>
      <div class="d-flex justify-content-center mt-5">
        <button class="btn btn-lg btn-outline-light" type="submit">Add</button>
      </div>
    </form>
  </div>
{% endblock %}

templates/accounts/company_update.html
{% extends 'base.html' %}

{% block content %}
  <div class="row g-3 mb-5">
    <h1 class="display-1">Change Your Company</h1>
    <form class="row g-3" action="{% url 'accounts:company_update' company.pk %}" method="post">
      {% csrf_token %}
      {{ form.errors }}
      <div class="col-12 col-lg-6">
        <label class="form-label" for="id_name">Name of Company</label>
        <input type="text" class="form-control" name="name" id="id_name" maxlength="128" required value="{{ company.name }}" placeholder="Enter your company name">
      </div>
      <div class="col-12 col-lg-6">
        <label class="form-label" for="id_email">Company Email</label>
        <input type="text" class="form-control" name="email" id="id_email" maxlength="128" required value="{{ company.email }}" placeholder="Enter your company email">
      </div>
      <div class="col-12 col-lg-6">
        <label class="form-label" for="id_color">Choose Provided Services</label>
        {% regroup form.services.field.queryset by get_category_display as categories %}
        {% for category in categories %}
          <h6 class="mt-2">{{ category.grouper }}</h6>
          {% for service in category.list %}
            <div class="form-check">
              <input class="form-check-input" type="checkbox" name="services" {% if service.id in form.services.value %}checked{% endif %} name="services" value="{{ service.id }}" id="id_services_{{ service.id|add:-1 }}">
              <label class="form-check-label text-white" for="id_services_{{ service.id|add:-1 }}">{{ service.name }}</label>
            </div>
          {% endfor %}
        {% endfor %}
      </div>
      <div class="d-flex justify-content-center mt-5">
        <button class="btn btn-lg btn-outline-light" type="submit">Save</button>
      </div>
    </form>
  </div>
{% endblock %}

templates/accounts/password_change.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="mx-auto col-lg-8 card bg-dark">
    <div class="row">
      <div class="col-lg-6 col-md-5 col-sm-12">
        <div class="card-body">
          <h1>Change password</h1>
          <p>Text</p>
        </div>
      </div>
      <div class="col-lg-6 col-md-7 col-sm-12">
        <div class="card-body">
          <form class="row g-3" action="{% url 'accounts:password_change' %}" method="post">
            {% csrf_token %}
            {{ form.errors }}
            <div class="col-12">
              <label class="form-label" for="id_old_password">Old password</label>
              <input type="password" class="form-control" name="old_password" id="id_old_password" required placeholder="Your old password">
            </div>
            <div class="col-12">
              <label class="form-label" for="id_new_password1">New password</label>
              <input type="password" class="form-control" name="new_password1" id="id_new_password1" required placeholder="8-20 symbols">
            </div>
            <div class="col-12">
              <label class="form-label" for="id_new_password2">New password (again)</label>
              <input type="password" class="form-control" name="new_password2" id="id_new_password2" required placeholder="8-20 symbols">
            </div>
            <div class="d-flex justify-content-center">
              <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
            </div>
          </form>
        </div>
      </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/accounts/sign_in.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="mx-auto col-lg-8 card bg-dark">
    <div class="row">
      <div class="col-lg-6 col-md-5 col-sm-12">
        <div class="card-body">
          <h1>Sign In</h1>
          <p>Text</p>
        </div>
      </div>
      <div class="col-lg-6 col-md-7 col-sm-12">
        <div class="card-body">
          <form id="sign_in" class="row g-3" action="{% url 'accounts:sign_in' %}" method="post">
            {% csrf_token %}
            {% if form.non_field_errors %}
              <div class="alert alert-danger" role="alert">
                Wrong username and (or) password!
              </div>
            {% endif %}
            <div class="col-12">
              <label class="form-label" for="id_email">Email</label>
              <input type="email" class="form-control" name="username" id="id_email" required placeholder="johnlennon@gmail.com">
            </div>
            <div class="col-12">
              <label class="form-label" for="id_password1">Password</label>
              <input type="password" class="form-control" name="password" id="id_password1" required placeholder="8-20 symbols">
            </div>
            <div class="col-md-6">
              <div class="form-check">
                <input class="form-check-input" type="checkbox" name="remember_me" id="remember_me">
                <label class="form-check-label" for="remember_me">Remember me</label>
              </div>
            </div>
            <div class="col-md-6 text-end">
              <a href="">Forgot password?</a>
            </div>
            <div class="d-flex justify-content-center">
              <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
            </div>
            <div class="col-12">
              If you are new user, then <a href="{% url 'accounts:sign_up' %}" class="link-danger">sign up</a>.
            </div>
          </form>
        </div>
      </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/accounts/sign_up.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="mx-auto col-lg-8 card bg-dark">
    <div class="row">
      <div class="col-lg-6 col-md-5 col-sm-12">
        <div class="card-body">
          <h1 class="mb-4">Sign Up</h1>
          <h6>Password</h6>
          <p>{{ form.password1.help_text }}</p>
        </div>
      </div>
      <div class="col-lg-6 col-md-7 col-sm-12">
        <div class="card-body">
          <form id="sign_up" class="row g-3" action="{% url 'accounts:sign_up' %}" method="post">
            {% csrf_token %}
            {{ form.errors }}
            <div class="col-md-6">
              <label for="id_first_name" class="form-label" >First name</label>
              <input type="text" class="form-control" name="first_name" id="id_first_name" maxlength="150" required placeholder="John">
            </div>
            <div class="col-md-6">
              <label for="id_last_name" class="form-label">Last name</label>
              <input type="text" class="form-control" name="last_name" id="id_last_name" maxlength="150" required placeholder="Lennon">
            </div>
            <div class="col-12">
              <label class="form-label" for="id_email">Email</label>
              <input type="email" class="form-control" name="email" id="id_email" required placeholder="johnlennon@gmail.com">
            </div>
            <div class="col-md-6">
              <label class="form-label" for="id_password1">Password</label>
              <input type="password" class="form-control" name="password1" id="id_password1" required placeholder="8-20 symbols">
            </div>
            <div class="col-md-6">
              <label class="form-label" for="id_password2">Password (again)</label>
              <input type="password" class="form-control" name="password2" id="id_password2" required placeholder="">
            </div>
            <div class="d-flex justify-content-center mt-4">
              <button class="w-100 btn btn-lg btn-primary" type="submit">Sign Up</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

<script>
    const form = document.querySelector('#sign_up');
    const errorDiv = document.querySelector('#show-error');
    const email = document.querySelector('#id_email');
    const firstPassword = document.querySelector('#id_password1');
    let firstPasswordTooltip = document.querySelector('#id_password1_tooltip')
    const secondPassword = document.querySelector('#id_password2');
    let secondPasswordTooltip = document.querySelector('#id_password2_tooltip');


    form.addEventListener('submit', (error) => {
        if (firstPassword.value.length < 8 || firstPassword.value.length > 20) {
            error.preventDefault();
            firstPassword.classList.add("is-invalid");
            firstPasswordTooltip.classList.remove('invisible');
            firstPasswordTooltip.innerText = 'Password length must be 8-20 symbols!';
        };

        if (firstPassword.value !== secondPassword.value) {
            error.preventDefault();
            secondPassword.classList.add("is-invalid");
            secondPasswordTooltip.classList.remove('invisible');
            secondPasswordTooltip.innerText = 'Passwords does not match!';
        };
    });
</script>