accounts/urls.py
from django.contrib.auth.views import TemplateView, PasswordChangeView, LogoutView
from django.urls import path, reverse_lazy

from .views import (
    SignInView, SignUpView,
    CarListView, CarDetailView, CarCreateView, CarUpdateView, CarDeleteView,
    CompanyListView, CompanyDetailView, CompanyCreateView, CompanyUpdateView, CompanyDeleteView
)


app_name = 'accounts'

urlpatterns = [
    path('sign-up', SignUpView.as_view(), name='sign_up'),
    path('sign-in', SignInView.as_view(), name='sign_in'),
    path('choose-account', TemplateView.as_view(
        template_name='accounts/choose_account.html'),
        name='choose_account'
    ),
    path('change-password', PasswordChangeView.as_view(
        template_name='accounts/password_change.html',
        success_url=reverse_lazy('dashboard:main'),
        extra_context={'password_change': True}
    ), name='password_change'),
    path('logout', LogoutView.as_view(
        next_page='/'
    ), name='logout'),

    path('cars', CarListView.as_view(), name='car_list'),
    path('cars/<int:pk>', CarDetailView.as_view(), name='car_detail'),
    path('cars/create', CarCreateView.as_view(), name='car_create'),
    path('cars/<int:pk>/edit', CarUpdateView.as_view(), name='car_edit'),
    path('cars/<int:pk>/delete', CarDeleteView.as_view(), name='car_delete'),

    path('companies', CompanyListView.as_view(), name='company_list'),
    path('companies/<int:pk>', CompanyDetailView.as_view(), name='company_detail'),
    path('companies/create', CompanyCreateView.as_view(), name='company_create'),
    path('companies/<int:pk>/edit', CompanyUpdateView.as_view(), name='company_edit'),
    path('companies/<int:pk>/delete', CompanyDeleteView.as_view(), name='company_delete'),
]

project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('apps.dashboard.urls', namespace='dashboard')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('auctions/', include('apps.auctions.urls', namespace='auctions')),
    path('offers/', include('apps.offers.urls', namespace='offers')),
]

if settings.DEBUG:
    urlpatterns += [
        path('admin/', admin.site.urls),
        path('__debug__/', include('debug_toolbar.urls')),
    ]

apps/auctions/models.py
from datetime import timedelta

from django.db import models
from django.urls import reverse
from django_q.models import Schedule


class Service(models.Model):
    CATEGORY_CHOICES = (
        (1, "Repair"),
        (2, "Maintenance"),
    )

    name = models.CharField(max_length=128)
    category = models.PositiveSmallIntegerField(choices=CATEGORY_CHOICES)

    def __str__(self):
        return f'{str(self.get_category_display())}. {self.name}'


class Auction(models.Model):
    FAST = 10
    NORMAL = 60
    SLOW = 1440

    DURATION_CHOICES = (
        (FAST, '10 minutes'),
        (NORMAL, '1 hour'),
        (SLOW, '1 day'),
    )

    car = models.ForeignKey('accounts.Car', on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    start_cost = models.PositiveSmallIntegerField()

    datetime_start = models.DateTimeField(auto_now_add=True)
    duration_choice = models.PositiveSmallIntegerField(choices=DURATION_CHOICES, default=FAST)
    datetime_end = models.DateTimeField(blank=True, null=True)

    is_ended = models.BooleanField(default=False)

    def __str__(self):
        return f'Auction on {self.service} for {self.car.client.user.email}'

    def get_absolute_url(self):
        return reverse('auctions:auction_detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        if not self.pk:
            super(Auction, self).save(*args, **kwargs)

        if not self.datetime_end:
            datetime_end = self.datetime_start + timedelta(minutes=self.duration_choice)
            self.datetime_end = datetime_end

        super(Auction, self).save(*args, **kwargs)


class Order(models.Model):
    offer = models.OneToOneField('offers.Offer', on_delete=models.CASCADE)
    datetime_start = models.DateTimeField(auto_now_add=True)
    is_completed = models.BooleanField(default=False)

    def __str__(self):
        return f'Order №{self.pk}'

templates/auth.html
{% load static %}

<div class="card bg-dark p-3 mb-3">
  <div class="row g-0">
    <div class="col-lg-8 col-md-6 col-sm-12">
      <div class="card-body">
        <h1 class="card-title">DetailingAuction</h1>
        <p class="mt-3 card-text">
          We are the company, that helps people to make search of detailing service for your car easier.
          We bring together hundreds of widely known car's repair and maintenance companies.
        </p>
        <p class="card-text"><small class="text-muted">Иван Михайлович <a href="mailto:alkorol98@mail.ru">alkorol98@mail.ru</a></small></p>
        <div class="row row-cols-auto">
          <div class="col mt-3">
            <a href="https://play.google.com/store/">
              <img class="img-fluid" src="{% static 'img/google-play.png' %}" style="height: 5rem;">
            </a>
          </div>
          <div class="col mt-3">
            <a href="https://apps.apple.com">
              <img class="img-fluid" src="{% static 'img/app-store.png' %}" style="height: 5rem;">
            </a>
          </div>  
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-md-6 col-sm-12">
      <div class="card-body">
        <div class="enter">
          <div class="forms">
            <div class="form login px-1">
              <div class="btn-group btn-group-lg mb-3 d-flex" role="group">
                <button type="button" class="btn btn-primary w-100">Вход</button>
                <button type="button" class="btn btn-outline-primary w-100 signup-link">Регистрация</button>
              </div>
              <form class="form-signin" action="{% url 'sign_in' %}" method="post">
                {% csrf_token %}
                {% if login_form.non_field_errors %}
                  <div class="alert alert-danger" role="alert">
                    Неверно введены логин или пароль!
                  </div>
                {% endif %}
                <div class="form-floating">
                  <input type="text" class="form-control {% if login_form.non_field_errors %}is-invalid{% endif %}" name="username" autofocus required id="id_username" placeholder="username">
                  <label for="id_username">Логин</label>
                </div>
                <div class="form-floating">
                  <input type="password" class="form-control {% if login_form.non_field_errors %}is-invalid{% endif %}" name="password" required id="id_password" placeholder="password">
                  <label for="id_for_password">Пароль</label>
                </div>
                <div class="mb-3 row">
                  <div class="col">
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                      <label class="form-check-label" for="flexCheckDefault">Запомнить меня</label>
                    </div>
                  </div>
                  <div class="col text-end">
                    <a href="#">Забыли пароль?</a>
                  </div>
                </div>
                <div class="mb-3 d-flex justify-content-center">
                  <button class="w-100 btn btn-lg btn-primary" type="submit">Войти</button>
                </div>
              </form>
            </div>
            <div class="form signup px-1">
              <div class="btn-group btn-group-lg mb-3 d-flex" role="group">
                <button type="button" class="btn btn-outline-primary w-100 login-link">Вход</button>
                <button type="button" class="btn btn-primary w-100">Регистрация</button>
              </div>
              <form id="sign_up" class="form-signin" action="{% url 'sign_up' %}" method="post">
                {% csrf_token %}
                <div class="form-floating">     
                  <input type="text" class="form-control" name="username" id="id_username" autofocus required placeholder="username">
                  <label for="id_username">Логин</label>
                  <div class="invalid-tooltip invisible"></div>
                </div>
                <div class="form-floating">
                  <input type="password" class="form-control" name="password1" id="id_for_password1" required placeholder="password">
                  <label for="id_for_password1">Пароль</label>
                  <div id="id_for_password1_tooltip" class="invalid-tooltip invisible"></div>
                </div>
                <div class="form-floating">
                  <input type="password" class="form-control" name="password2" id="id_for_password2" required placeholder="password">
                  <label for="id_for_password2">Пароль (повторно)</label>
                  <div id="id_for_password2_tooltip" class="invalid-tooltip invisible"></div>
                </div>
                <div class="mb-3 d-flex justify-content-center">
                  <button class="w-100 btn btn-lg btn-primary" type="submit">Зарегистрироваться</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  const enter = document.querySelector(".enter"),
      signUp = document.querySelector(".signup-link"),
      login = document.querySelector(".login-link");

  signUp.addEventListener("click", () => {
      enter.classList.add("active");
  });

  login.addEventListener("click", () => {
      enter.classList.remove("active");
  });

  const form = document.querySelector('#sign_up');
  const errorDiv = document.querySelector('#show-error');
  const username = document.querySelector('#id_username');
  const firstPassword = document.querySelector('#id_for_password1');
  var firstPasswordTooltip = document.querySelector('#id_for_password1_tooltip')
  const secondPassword = document.querySelector('#id_for_password2'); 
  var secondPasswordTooltip = document.querySelector('#id_for_password2_tooltip');
  

  form.addEventListener('submit', (error) => {
      if (firstPassword.value.length < 8 || firstPassword.value.length > 20) {
          error.preventDefault();
          firstPassword.classList.add("is-invalid");
          firstPasswordTooltip.classList.remove('invisible');
          firstPasswordTooltip.innerText = 'Длина пароля должна быть 8-20 символов!';
      };

      if (firstPassword.value !== secondPassword.value) {
          error.preventDefault();
          secondPassword.classList.add("is-invalid");
          secondPasswordTooltip.classList.remove('invisible');
          secondPasswordTooltip.innerText = 'Пароли не совпадают!';
      };
  });
  
</script>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <title>DetailingAuctionPlatform</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  {% block static %}
  {% endblock %}
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
  <nav class="navbar navbar-expand-lg navbar-dark p-5">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">DetailingAuctionPlatform</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
        aria-controls="navbarText" aria-expanded="false">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:password_change' %}">Change password</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:sign_in' %}">Sign In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:sign_up' %}">Sign Up</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <div class="container-sm">
    {% block content %}
    {% endblock %}
  </div>
</body>

</html>

templates/car_service.html
{% load static %}

<div class="row">
  <div class="col-lg-4 col-md-7 col-sm-6">
    <div class="row row-cols-1 g-2">
      <div class="col">
        <div class="card bg-dark">
          <div class="card-body">
            <dl class="row lead">
              <dt class="col-sm-5">Brand</dt>
              <dd class="col-sm-7">{{ car.brand }}</dd>
              <dt class="col-sm-5">Model</dt>
              <dd class="col-sm-7">{{ car.model }}</dd>
              <dt class="col-sm-5">Release year</dt>
              <dd class="col-sm-7">{{ car.release_year }}</dd>
              <dt class="col-sm-5">Color</dt>
              <dd class="col-sm-7">{{ car.color }}</dd>
            </dl>
            <a href="#" class="btn btn-primary">Edit</a>
            <a href="#" class="btn btn-danger">Delete</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-8 col-md-7 col-sm-6">
    <div class="row">
      <div class="card bg-dark">
        <h2 class="card-title ms-3 mt-4">Order a service</h2>
        <div class="row g-0">
          <div class="col-md-5">
            <div class="card-body">
              <form method="post" hx-post="{% url 'auction_create' %}" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}' hx-target="#detail-list">
                <div class="row g-3">
                  <div class="col-12">
                    {% regroup services by get_category_display as categories %}
                    <select class="form-select" id="id_chosen_service" name="chosen_service">
                      <option selected>Choose a service</option>
                      {% for category in categories %}
                        <optgroup label="{{ category.grouper }}">
                          {% for service in category.list %}
                            <option value="{{ service.id }}">{{ service.name }}</option>
                          {% endfor %}
                        </optgroup>
                      {% endfor %}
                    </select>
                  </div>
                  <div class="col-12">
                    <button id="auction_create" class="btn btn-primary btn" type="submit">Start auction</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
          <div class="col-md-7">
            <div class="card-body" id="detail-list" hx-get="{% url 'auction_list' %}" hx-trigger="load">
            </div>
          </div>
        </div>
      </div>
    </div>
    <div hx-get="{% url 'order_list' status='in-progress' %}" hx-trigger="load"></div>
    <div hx-get="{% url 'order_list' status='completed' %}" hx-trigger="load"></div>
  </div>
</div>
  

templates/create_account.html
{% load static %}
<html>

<head>
  <title>основное </title>
  <link rel="stylesheet" href="{% static 'base.css' %}">
</head>

<body>
  <a name="start">
    <h2>Добрый день, <a href="ChangeProfileInfo.html">{{ user }}</a></h2>
  </a>
  <div class="row">
    <div class="col">
      <h1>Введите основные данные вашего автомобиля</h1>
      <form method="post">
        {% csrf_token %}
        <table>
          <tbody>
            <tr>
              <td><b style="margin-right: 15px;">Марка:</b></td>
              <td>{{ form.auto }}</td>
            </tr>
            <tr>
              <td><b style="margin-right: 15px;">Модель:</b> </td>
              <td>{{ form.model }}</td>
            </tr>
            <tr>
              <td><b style="margin-right: 15px;">Цвет:</b> </td>
              <td>{{ form.color }}</td>
            </tr>
            <tr>
              <td><b style="margin-right: 15px;">Год выпуска:</b> </td>
              <td>{{ form.release_year }}</td>
            </tr>
          </tbody>
        </table>
        <button type="submit">Сохранить</button>
      </form>
    </div>
  </div>
</body>

</html>