accounts/urls.py
from django.contrib.auth.views import TemplateView, PasswordChangeView, LogoutView
from django.urls import path, reverse_lazy

from .views import (
    SignInView, SignUpView,
    CarListView, CarDetailView, CarCreateView, CarUpdateView, CarDeleteView,
    CompanyListView, CompanyDetailView, CompanyCreateView, CompanyUpdateView, CompanyDeleteView
)


app_name = 'accounts'

urlpatterns = [
    path('sign-up', SignUpView.as_view(), name='sign_up'),
    path('sign-in', SignInView.as_view(), name='sign_in'),
    path('choose-account', TemplateView.as_view(
        template_name='accounts/choose_account.html'),
        name='choose_account'
    ),
    path('change-password', PasswordChangeView.as_view(
        template_name='accounts/password_change.html',
        success_url=reverse_lazy('dashboard:main'),
        extra_context={'password_change': True}
    ), name='password_change'),
    path('logout', LogoutView.as_view(
        next_page='/'
    ), name='logout'),

    path('cars', CarListView.as_view(), name='car_list'),
    path('cars/<int:pk>', CarDetailView.as_view(), name='car_detail'),
    path('cars/create', CarCreateView.as_view(), name='car_create'),
    path('cars/<int:pk>/edit', CarUpdateView.as_view(), name='car_edit'),
    path('cars/<int:pk>/delete', CarDeleteView.as_view(), name='car_delete'),

    path('companies', CompanyListView.as_view(), name='company_list'),
    path('companies/<int:pk>', CompanyDetailView.as_view(), name='company_detail'),
    path('companies/create', CompanyCreateView.as_view(), name='company_create'),
    path('companies/<int:pk>/edit', CompanyUpdateView.as_view(), name='company_edit'),
    path('companies/<int:pk>/delete', CompanyDeleteView.as_view(), name='company_delete'),
]

apps/auctions/urls.py
from django.urls import path

from .views import AuctionCreateView, AuctionDetailView, AuctionListView, AuctionUpdateView, delete_auction


app_name = 'auctions'

urlpatterns = [
    path('list', AuctionListView.as_view(), name='auction_list'),
    path('create', AuctionCreateView.as_view(), name='auction_create'),
    path('<int:pk>', AuctionDetailView.as_view(), name='auction_detail'),
    path('<int:pk>/update', AuctionUpdateView.as_view(), name='auction_update'),
    path('<int:pk>/delete/<int:from_detail>', delete_auction, name='auction_delete'),
]

apps/dashboard/urls.py
from django.urls import path

from .views import MainView


app_name = 'dashboard'

urlpatterns = [
    path('', MainView.as_view(), name='main'),
]

apps/offers/urls.py
from django.urls import path

from .views import OfferCreateView, OfferListView


app_name = 'offers'

urlpatterns = [
    path('list', OfferListView.as_view(), name='offer_list'),
    path('create/for-auction=<int:auction_pk>', OfferCreateView.as_view(), name='offer_create'),
]

project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('apps.dashboard.urls', namespace='dashboard')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('auctions/', include('apps.auctions.urls', namespace='auctions')),
    path('offers/', include('apps.offers.urls', namespace='offers')),
]

if settings.DEBUG:
    urlpatterns += [
        path('admin/', admin.site.urls),
        path('__debug__/', include('debug_toolbar.urls')),
    ]

apps/dashboard/models.py
from django.db import models

# Create your models here.

apps/dashboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.shortcuts import redirect
from django.urls import reverse

from apps.accounts.models import Client, Representative, Car, Company
from apps.auctions.models import Auction, Order
from apps.offers.models import Offer


class MainView(LoginRequiredMixin, TemplateView):
    redirect_field_name = ''
    template_name = 'dashboard/main.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()

        user = request.user

        if user.is_staff:
            return redirect(reverse('admin:index'))

        if not user.is_client and not user.is_representative:
            return redirect(reverse('accounts:choose_account'))

        return super(MainView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(MainView, self).get_context_data(**kwargs)
        user = self.request.user

        if user.is_client:
            client = Client.objects.get(user=user)
            cars = Car.objects.filter(client=client)

            context.update({
                'user_type': 'client',
                'client': client,
                'cars': cars,
                'auctions_in_progress': Auction.objects.filter(car__in=cars, is_ended=False),
                'auctions_closed': Auction.objects.filter(car__in=cars, is_ended=True),
                'orders': Order.objects.filter(offer__auction__car__in=cars)
            })

        if user.is_representative:
            representative = Representative.objects.get(user=user)
            company = Company.objects.get(representative=representative)
            offers = Offer.objects.filter(company=company).select_related('auction')

            context.update({
                'user_type': 'representative',
                'representative': representative,
                'company': company,
                'offers': offers,
                'orders': Order.objects.filter(offer__in=offers)
            })

        return context

dashboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.shortcuts import redirect
from django.urls import reverse

from accounts.models import Client, Representative, Car, Company
from auctions.models import Auction, Order
from offers.models import Offer


class MainView(LoginRequiredMixin, TemplateView):
    redirect_field_name = ''
    template_name = 'dashboard/main.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()

        user = request.user

        if user.is_staff:
            return redirect(reverse('admin:index'))

        if not user.is_client and not user.is_representative:
            return redirect(reverse('accounts:choose_account'))

        return super(MainView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(MainView, self).get_context_data(**kwargs)
        user = self.request.user

        if user.is_client:
            client = Client.objects.get(user=user)
            cars = Car.objects.filter(client=client)

            context.update({
                'user_type': 'client',
                'client': client,
                'cars': cars,
                'auctions_in_progress': Auction.objects.filter(car__in=cars, is_ended=False),
                'auctions_closed': Auction.objects.filter(car__in=cars, is_ended=True),
                'orders': Order.objects.filter(offer__auction__car__in=cars)
            })

        if user.is_representative:
            representative = Representative.objects.get(user=user)
            company = Company.objects.get(representative=representative)
            offers = Offer.objects.filter(company=company).select_related('auction')

            context.update({
                'user_type': 'representative',
                'representative': representative,
                'company': company,
                'offers': offers,
                'orders': Order.objects.filter(offer__in=offers)
            })

        return context

templates/dashboard/client.html
<div class="row mb-5">
  <h1>Hello, {{ client.user.full_name }}</h1>
</div>

<div class="row g-3 mb-5">
  <div class="col-12 col-sm-12 col-md-6 col-lg-4">
    <div class="card bg-dark">
      <h4 class="card-header">Cars</h4>
      <div class="card-body">
      {% csrf_token %}
        <ul class="list-group mb-3" id="car-list" >
          {% for car in cars %}
            <li class="list-group-item d-flex justify-content-between align-items-start">
              <div class="ms-2 me-auto">
                <div class="fw-bold">{{ car.brand }} {{ car.model }}</div>
                <div class="text-secondary"><small>{{ car.color }}, {{ car.release_year }}</small></div>
              </div>
              <div class="row g-1">
                <div class="col">
                  <a href="{% url 'accounts:car_edit' car.pk %}" class="btn btn-primary btn-sm">Edit</a>
                  <button type="submit" class="btn btn-danger btn-sm" hx-delete="{% url 'accounts:car_delete' car.pk %}" hx-confirm="Are you sure?" hx-target="#car-list" hx-swap="outerHTML swap:1s">Delete</button>
                </div>
              </div>
            </li>
          {% empty %}
            You have no cars yet.
          {% endfor %}
        </ul>
        <a href="{% url 'accounts:car_create' %}" class="btn btn-primary">Add new car</a>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card bg-dark">
      <h4 class="card-header">Auctions</h4>
      <div class="card-body">
        <h5 class="card-title">In progress</h5>
        <div class="card-text mb-3">
          <ul class="list-group list-group-flush">
            {% for auction in auctions_in_progress %}
              <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto my-auto">{{ auction.service.name }}</div>
                <div class="row g-1">
                  <div class="col">
                    <small>{{ auction.datetime_end }}</small>
                  </div>
                </div>
              </li>
            {% empty %}
              You have no current auctions.
            {% endfor %}
          </ul>
        </div>
        <h5 class="card-title">Closed</h5>
      <div class="card-text mb-3">
          <ul class="list-group list-group-flush">
            {% for auction in closed_auctions %}
              <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto my-auto">{{ auction.service.name }}</div>
                <div class="row g-1">
                  <div class="col">
                    <small>{{ auction.datetime_end }}</small>
                  </div>
                </div>
              </li>
            {% empty %}
              You have no closed auctions.
            {% endfor %}
          </ul>
        </div>
        <a href="{% url 'auctions:auction_list' %}" class="btn btn-primary">Go to auctions</a>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card bg-dark">
      <h4 class="card-header">Orders</h4>
      <div class="card-body">
        <div class="card-text mb-3">
          <ul class="list-group list-group-flush">
            {% for order in orders %}
              <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto my-auto">{{ order }}</div>
                <div class="row g-1">
                  <div class="col">
                    <small>{{ order.datetime_start }}</small>
                  </div>
                </div>
              </li>
            {% empty %}
              You have no current orders.
            {% endfor %}
          </ul>
        </div>
        <a href="" class="btn btn-primary">Go to orders</a>
      </div>
    </div>
  </div>
</div>

templates/dashboard/main.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
  <script src="{% static 'js/htmx.min.js' %}"></script>
{% endblock %}

{% block content %}
  {% if user_type == 'client' %}
    {% include 'dashboard/client.html' %}
  {% elif user_type == 'representative' %}
    {% include 'dashboard/representative.html' %}
  {% endif %}
{% endblock %}

templates/dashboard/representative.html
<div class="row mb-5">
  <h1>Hello, {{ representative.user.full_name }}</h1>
</div>

<div class="row g-3 mb-5">
  <div class="col-12 col-sm-12 col-md-6 col-lg-4">
    <div class="card bg-dark">
      <h4 class="card-header">Your company</h4>
      <div class="card-body">
        <h5 class="card-title">{{ company.name }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ company.email }}</h6>
        <p class="card-text">{{ company.description }}</p>
        <p class="card-text">
          <strong>Services:</strong>
          {% for service in company.services.all %}
            {{ service.name }}
          {% endfor %}
        </p>
        <a href="{% url 'accounts:company_edit' company.pk %}" class="btn btn-primary">Edit</a>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card bg-dark">
      <h4 class="card-header">Offers</h4>
      <div class="card-body">
        <div class="card-text mb-3">
          <ul class="list-group list-group-flush">
            {% for offer in offers %}
              <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto my-auto">{{ offer }}</div>
                <div class="row g-1">
                  <div class="col">
                    <small>{{ offer.cost }}, {{ offer.order_datetime_end }}</small>
                  </div>
                </div>
              </li>
            {% empty %}
              You have no current offers.
            {% endfor %}
          </ul>
        </div>
        <a href="{% url 'offers:offer_list' %}" class="btn btn-primary">Go to offers</a>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card bg-dark">
      <h4 class="card-header">Orders</h4>
      <div class="card-body">
        <div class="card-text mb-3">
          <ul class="list-group list-group-flush">
            {% for order in orders %}
              <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto my-auto">{{ order }}</div>
                <div class="row g-1">
                  <div class="col">
                    <small>{{ order.datetime_start }}</small>
                  </div>
                </div>
              </li>
            {% empty %}
              You have no current orders.
            {% endfor %}
          </ul>
        </div>
        <a href="" class="btn btn-primary">Go to orders</a>
      </div>
    </div>
  </div>
</div>